import type { Meeting } from '@/lib/types/meeting';

function deterministicInt(min: number, max: number, seed: number) {
  // Simple deterministic "random" function using seed
  const x = Math.sin(seed) * 10000;
  const normalized = (x - Math.floor(x));
  return Math.floor(normalized * (max - min + 1)) + min;
}

function daysInMonth(year: number, month0: number) {
  return new Date(year, month0 + 1, 0).getDate();
}

function deterministicUtcIsoIn(year: number, month0: number, seed: number) {
  const dmax = daysInMonth(year, month0);
  const d = deterministicInt(1, dmax, seed);
  const h = deterministicInt(0, 23, seed + 1);
  const m = deterministicInt(0, 59, seed + 2);
  const s = deterministicInt(0, 59, seed + 3);
  return new Date(Date.UTC(year, month0, d, h, m, s)).toISOString();
}

function twoDatesCurrentAndPrevMonthUTC() {
  const now = new Date();
  const y = now.getUTCFullYear();
  const m0 = now.getUTCMonth();              // 当前月（0-11）
  const prevY = m0 === 0 ? y - 1 : y;
  const prevM0 = m0 === 0 ? 11 : m0 - 1;     // 上个月

  const current = deterministicUtcIsoIn(y, m0, 123);
  const previous = deterministicUtcIsoIn(prevY, prevM0, 456);
  return { current, previous };
}

// Generate deterministic dates for this month and last month
const { current: currentMonthDate, previous: lastMonthDate } = twoDatesCurrentAndPrevMonthUTC();

// Generate additional deterministic dates for current month meetings
const now = new Date();
const currentYear = now.getUTCFullYear();
const currentMonth = now.getUTCMonth();
const currentMonthDate2 = deterministicUtcIsoIn(currentYear, currentMonth, 789);
const currentMonthDate3 = deterministicUtcIsoIn(currentYear, currentMonth, 101112);

// Generate date for month before last month (reserved for future mock data generation)
// const twoMonthsAgoYear = currentMonth <= 1 ? currentYear - 1 : currentYear;
// const twoMonthsAgoMonth = currentMonth <= 1 ? currentMonth + 10 : currentMonth - 2;
// const twoMonthsAgoDate = deterministicUtcIsoIn(twoMonthsAgoYear, twoMonthsAgoMonth, 131415);

// Generate additional deterministic dates for more meetings
const lastMonthYear = currentMonth === 0 ? currentYear - 1 : currentYear;
const lastMonth = currentMonth === 0 ? 11 : currentMonth - 1;
const lastMonthDate2 = deterministicUtcIsoIn(lastMonthYear, lastMonth, 161718);
const lastMonthDate3 = deterministicUtcIsoIn(lastMonthYear, lastMonth, 192021);

const currentMonthDate4 = deterministicUtcIsoIn(currentYear, currentMonth, 222324);
const currentMonthDate5 = deterministicUtcIsoIn(currentYear, currentMonth, 252627);
const currentMonthDate6 = deterministicUtcIsoIn(currentYear, currentMonth, 282930);

// Unused: reserved for future mock data generation
// const twoMonthsAgoDate2 = deterministicUtcIsoIn(twoMonthsAgoYear, twoMonthsAgoMonth, 313233);
// const twoMonthsAgoDate3 = deterministicUtcIsoIn(twoMonthsAgoYear, twoMonthsAgoMonth, 343536);

// Generate dates for month before the month before the last month (3 months ago)
const threeMonthsAgoYear = currentMonth <= 2 ? currentYear - 1 : currentYear;
const threeMonthsAgoMonth = currentMonth <= 2 ? currentMonth + 9 : currentMonth - 3;
const threeMonthsAgoDate1 = deterministicUtcIsoIn(threeMonthsAgoYear, threeMonthsAgoMonth, 373839);
const threeMonthsAgoDate2 = deterministicUtcIsoIn(threeMonthsAgoYear, threeMonthsAgoMonth, 404142);
const threeMonthsAgoDate3 = deterministicUtcIsoIn(threeMonthsAgoYear, threeMonthsAgoMonth, 434445);

/**
 * Mock Meetings Data for Demo
 */
export const MEETING_DATA: Meeting = {
  "status": "success",
  data: [
    {
      id: 123,
      uid: 'booking_uid_123',
      title: 'Consultation',
      description: 'Learn how to integrate scheduling into marketplace.',
      hosts: [
        {
          id: 1,
          name: 'Jane Doe',
          email: 'jane100@example.com',
          username: 'jane100',
          timeZone: 'America/Los_Angeles',
        },
      ],
      status: 'accepted',
      cancellationReason: 'User requested cancellation',
      cancelledByEmail: 'canceller@example.com',
      reschedulingReason: 'User rescheduled the event',
      rescheduledByEmail: 'rescheduler@example.com',
      rescheduledFromUid: 'previous_uid_123',
      rescheduledToUid: 'new_uid_456',
      start: threeMonthsAgoDate1,
      end: new Date(new Date(threeMonthsAgoDate1).getTime() + 60 * 60 * 1000).toISOString(),
      duration: 60,
      eventTypeId: 50,
      eventType: {
        id: 1,
        slug: 'some-event',
      },
      meetingUrl: 'https://meet.google.com/abc-defg-hij',
      location: 'https://meet.google.com/abc-defg-hij',
      absentHost: true,
      createdAt: threeMonthsAgoDate1,
      updatedAt: threeMonthsAgoDate1,
      metadata: {
        key: 'value',
      },
      rating: 4,
      icsUid: 'ics_uid_123',
      attendees: [
        {
          name: 'John Doe',
          email: 'john@example.com',
          timeZone: 'America/New_York',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567890',
        },
        {
          name: 'Alice Smith',
          email: 'alice.smith@example.com',
          timeZone: 'America/Chicago',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567891',
        },
      ],
      guests: ['guest1@example.com', 'guest2@example.com'],
      bookingFieldsResponses: {
        customField: 'customValue',
      },
    },
    {
      id: 124,
      uid: 'booking_uid_124',
      title: 'Product Demo',
      description: 'Demonstration of new features and capabilities.',
      hosts: [
        {
          id: 2,
          name: 'Alex Smith',
          email: 'alex.smith@example.com',
          username: 'alexsmith',
          timeZone: 'Europe/London',
        },
      ],
      status: 'completed',
      start: lastMonthDate,
      end: new Date(new Date(lastMonthDate).getTime() + 60 * 60 * 1000).toISOString(),
      duration: 60,
      eventTypeId: 51,
      eventType: {
        id: 2,
        slug: 'product-demo',
      },
      meetingUrl: 'https://zoom.us/j/1234567890?pwd=abcdef123456',
      location: 'https://zoom.us/j/1234567890?pwd=abcdef123456',
      absentHost: false,
      createdAt: new Date(new Date(lastMonthDate).getTime() - 15 * 60 * 1000).toISOString(),
      updatedAt: new Date(new Date(lastMonthDate).getTime() + 60 * 60 * 1000).toISOString(),
      metadata: {
        department: 'Sales',
        priority: 'high',
      },
      rating: 5,
      icsUid: 'ics_uid_124',
      attendees: [
        {
          name: 'Bob Johnson',
          email: 'bob.johnson@example.com',
          timeZone: 'America/Denver',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567892',
        },
        {
          name: 'Carol Williams',
          email: 'carol.williams@example.com',
          timeZone: 'America/Los_Angeles',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567893',
        },
        {
          name: 'David Brown',
          email: 'david.brown@example.com',
          timeZone: 'America/New_York',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567894',
        },
      ],
      guests: ['observer@example.com'],
      bookingFieldsResponses: {
        company: 'TechCorp Inc',
        role: 'CTO',
        interests: 'AI, Machine Learning',
      },
    },
    {
      id: 125,
      uid: 'booking_uid_125',
      title: 'Team Standup',
      description: 'Daily team synchronization meeting.',
      hosts: [
        {
          id: 3,
          name: 'Maria Garcia',
          email: 'maria.garcia@example.com',
          username: 'mariag',
          timeZone: 'America/New_York',
        },
      ],
      status: 'cancelled',
      cancellationReason: 'Host unavailable due to emergency',
      cancelledByEmail: 'maria.garcia@example.com',
      start: currentMonthDate2,
      end: new Date(new Date(currentMonthDate2).getTime() + 30 * 60 * 1000).toISOString(),
      duration: 30,
      eventTypeId: 52,
      eventType: {
        id: 3,
        slug: 'team-standup',
      },
      meetingUrl: 'https://app.cal.com/video/team-standup-xyz',
      location: 'https://app.cal.com/video/team-standup-xyz',
      absentHost: true,
      createdAt: new Date(new Date(currentMonthDate2).getTime() - 30 * 60 * 1000).toISOString(),
      updatedAt: new Date(new Date(currentMonthDate2).getTime() - 15 * 60 * 1000).toISOString(),
      metadata: {
        team: 'Engineering',
        recurring: true,
      },
      rating: 0,
      icsUid: 'ics_uid_125',
      attendees: [
        {
          name: 'John Doe',
          email: 'john@example.com',
          timeZone: 'America/New_York',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567890',
        },
        {
          name: 'Alice Smith',
          email: 'alice.smith@example.com',
          timeZone: 'America/Chicago',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567891',
        },
        {
          name: 'Bob Johnson',
          email: 'bob.johnson@example.com',
          timeZone: 'America/Denver',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567892',
        },
      ],
      guests: [],
      bookingFieldsResponses: {
        team: 'Engineering',
        project: 'Mobile App',
      },
    },
    {
      id: 126,
      uid: 'booking_uid_126',
      title: 'Client Onboarding',
      description: 'Welcome session for new enterprise client.',
      hosts: [
        {
          id: 4,
          name: 'Robert Kim',
          email: 'robert.kim@example.com',
          username: 'robertk',
          timeZone: 'Asia/Tokyo',
        },
      ],
      status: 'rescheduled',
      reschedulingReason: 'Client requested different time slot',
      rescheduledByEmail: 'client.manager@example.com',
      rescheduledFromUid: 'booking_uid_126_old',
      rescheduledToUid: 'booking_uid_126',
      start: currentMonthDate3,
      end: new Date(new Date(currentMonthDate3).getTime() + 90 * 60 * 1000).toISOString(),
      duration: 90,
      eventTypeId: 53,
      eventType: {
        id: 4,
        slug: 'client-onboarding',
      },
      meetingUrl: 'https://meet.google.com/xyz-mnop-qrs',
      location: 'https://meet.google.com/xyz-mnop-qrs',
      absentHost: false,
      createdAt: new Date(new Date(currentMonthDate3).getTime() - 4 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(new Date(currentMonthDate3).getTime() - 4 * 60 * 60 * 1000).toISOString(),
      metadata: {
        clientTier: 'Enterprise',
        region: 'APAC',
        accountManager: 'Robert Kim',
      },
      rating: 4,
      icsUid: 'ics_uid_126',
      attendees: [
        {
          name: 'Carol Williams',
          email: 'carol.williams@example.com',
          timeZone: 'America/Los_Angeles',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567893',
        },
        {
          name: 'David Brown',
          email: 'david.brown@example.com',
          timeZone: 'America/New_York',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567894',
        },
        {
          name: 'Eve Wilson',
          email: 'eve.wilson@example.com',
          timeZone: 'America/Chicago',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567895',
        },
      ],
      guests: ['legal@example.com', 'finance@example.com'],
      bookingFieldsResponses: {
        company: 'Enterprise Solutions Ltd',
        industry: 'Financial Services',
        teamSize: '500+',
        budget: 'Enterprise',
        timeline: 'Q4 2024',
      },
    },
    {
      id: 127,
      uid: 'booking_uid_127',
      title: 'Sales Pitch',
      description: 'Presenting our solution to potential enterprise client.',
      hosts: [
        {
          id: 5,
          name: 'Sarah Wilson',
          email: 'sarah.wilson@example.com',
          username: 'sarahw',
          timeZone: 'America/New_York',
        },
      ],
      status: 'completed',
      start: lastMonthDate2,
      end: new Date(new Date(lastMonthDate2).getTime() + 45 * 60 * 1000).toISOString(),
      duration: 45,
      eventTypeId: 54,
      eventType: {
        id: 5,
        slug: 'sales-pitch',
      },
      meetingUrl: 'https://zoom.us/j/9876543210?pwd=xyz789abc456',
      location: 'https://zoom.us/j/9876543210?pwd=xyz789abc456',
      absentHost: false,
      createdAt: new Date(new Date(lastMonthDate2).getTime() - 30 * 60 * 1000).toISOString(),
      updatedAt: new Date(new Date(lastMonthDate2).getTime() + 45 * 60 * 1000).toISOString(),
      metadata: {
        department: 'Sales',
        priority: 'high',
        leadSource: 'Website',
      },
      rating: 4,
      icsUid: 'ics_uid_127',
      attendees: [
        {
          name: 'John Doe',
          email: 'john@example.com',
          timeZone: 'America/New_York',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567890',
        },
        {
          name: 'Bob Johnson',
          email: 'bob.johnson@example.com',
          timeZone: 'America/Denver',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567892',
        },
      ],
      guests: ['decision.maker@example.com'],
      bookingFieldsResponses: {
        company: 'Global Corp',
        role: 'VP Engineering',
        budget: 'High',
        timeline: 'Q1 2025',
      },
    },
    {
      id: 128,
      uid: 'booking_uid_128',
      title: 'Technical Review',
      description: 'Deep dive into technical implementation details.',
      hosts: [
        {
          id: 6,
          name: 'David Chen',
          email: 'david.chen@example.com',
          username: 'davidc',
          timeZone: 'Asia/Shanghai',
        },
      ],
      status: 'accepted',
      start: currentMonthDate4,
      end: new Date(new Date(currentMonthDate4).getTime() + 120 * 60 * 1000).toISOString(),
      duration: 120,
      eventTypeId: 55,
      eventType: {
        id: 6,
        slug: 'technical-review',
      },
      meetingUrl: 'https://app.cal.com/video/tech-review-456',
      location: 'https://app.cal.com/video/tech-review-456',
      absentHost: false,
      createdAt: currentMonthDate4,
      updatedAt: currentMonthDate4,
      metadata: {
        department: 'Engineering',
        complexity: 'High',
        reviewType: 'Architecture',
      },
      rating: 0,
      icsUid: 'ics_uid_128',
      attendees: [
        {
          name: 'Alice Smith',
          email: 'alice.smith@example.com',
          timeZone: 'America/Chicago',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567891',
        },
        {
          name: 'Carol Williams',
          email: 'carol.williams@example.com',
          timeZone: 'America/Los_Angeles',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567893',
        },
        {
          name: 'David Brown',
          email: 'david.brown@example.com',
          timeZone: 'America/New_York',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567894',
        },
        {
          name: 'Eve Wilson',
          email: 'eve.wilson@example.com',
          timeZone: 'America/Chicago',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567895',
        },
      ],
      guests: [],
      bookingFieldsResponses: {
        project: 'Microservices Migration',
        urgency: 'Medium',
        teamSize: '8',
      },
    },
    {
      id: 129,
      uid: 'booking_uid_129',
      title: 'Customer Support',
      description: 'Resolving customer issues and providing assistance.',
      hosts: [
        {
          id: 7,
          name: 'Emma Davis',
          email: 'emma.davis@example.com',
          username: 'emmad',
          timeZone: 'Europe/London',
        },
      ],
      status: 'completed',
      start: threeMonthsAgoDate2,
      end: new Date(new Date(threeMonthsAgoDate2).getTime() + 30 * 60 * 1000).toISOString(),
      duration: 30,
      eventTypeId: 56,
      eventType: {
        id: 7,
        slug: 'customer-support',
      },
      meetingUrl: 'https://meet.google.com/def-uvwx-yz1',
      location: 'https://meet.google.com/def-uvwx-yz1',
      absentHost: false,
      createdAt: new Date(new Date(threeMonthsAgoDate2).getTime() - 10 * 60 * 1000).toISOString(),
      updatedAt: new Date(new Date(threeMonthsAgoDate2).getTime() + 30 * 60 * 1000).toISOString(),
      metadata: {
        department: 'Support',
        priority: 'Medium',
        issueType: 'Technical',
      },
      rating: 5,
      icsUid: 'ics_uid_129',
      attendees: [
        {
          name: 'Bob Johnson',
          email: 'bob.johnson@example.com',
          timeZone: 'America/Denver',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567892',
        },
        {
          name: 'Eve Wilson',
          email: 'eve.wilson@example.com',
          timeZone: 'America/Chicago',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567895',
        },
      ],
      guests: [],
      bookingFieldsResponses: {
        issue: 'Login Problems',
        severity: 'Medium',
        account: 'Premium',
      },
    },
    {
      id: 130,
      uid: 'booking_uid_130',
      title: 'Project Kickoff',
      description: 'Starting a new project with the development team.',
      hosts: [
        {
          id: 8,
          name: 'Alex Johnson',
          email: 'alex.johnson@example.com',
          username: 'alexj',
          timeZone: 'America/Los_Angeles',
        },
      ],
      status: 'completed',
      start: currentMonthDate5,
      end: new Date(new Date(currentMonthDate5).getTime() + 90 * 60 * 1000).toISOString(),
      duration: 90,
      eventTypeId: 57,
      eventType: {
        id: 8,
        slug: 'project-kickoff',
      },
      meetingUrl: 'https://zoom.us/j/5555666677?pwd=qwerty123456',
      location: 'https://zoom.us/j/5555666677?pwd=qwerty123456',
      absentHost: false,
      createdAt: new Date(new Date(currentMonthDate5).getTime() - 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(new Date(currentMonthDate5).getTime() + 90 * 60 * 1000).toISOString(),
      metadata: {
        department: 'Product',
        projectPhase: 'Initiation',
        budget: 'Large',
      },
      rating: 4,
      icsUid: 'ics_uid_130',
      attendees: [
        {
          name: 'John Doe',
          email: 'john@example.com',
          timeZone: 'America/New_York',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567890',
        },
        {
          name: 'Alice Smith',
          email: 'alice.smith@example.com',
          timeZone: 'America/Chicago',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567891',
        },
        {
          name: 'Bob Johnson',
          email: 'bob.johnson@example.com',
          timeZone: 'America/Denver',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567892',
        },
        {
          name: 'Carol Williams',
          email: 'carol.williams@example.com',
          timeZone: 'America/Los_Angeles',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567893',
        },
      ],
      guests: ['stakeholder@example.com'],
      bookingFieldsResponses: {
        project: 'Mobile App Redesign',
        timeline: '6 months',
        teamSize: '12',
      },
    },
    {
      id: 131,
      uid: 'booking_uid_131',
      title: 'Training Session',
      description: 'Training new team members on company processes.',
      hosts: [
        {
          id: 9,
          name: 'Jennifer Lee',
          email: 'jennifer.lee@example.com',
          username: 'jenniferl',
          timeZone: 'America/Chicago',
        },
      ],
      status: 'cancelled',
      cancellationReason: 'Trainer sick, rescheduled for next week',
      cancelledByEmail: 'jennifer.lee@example.com',
      start: lastMonthDate3,
      end: new Date(new Date(lastMonthDate3).getTime() + 180 * 60 * 1000).toISOString(),
      duration: 180,
      eventTypeId: 58,
      eventType: {
        id: 9,
        slug: 'training-session',
      },
      meetingUrl: 'https://app.cal.com/video/training-session-789',
      location: 'https://app.cal.com/video/training-session-789',
      absentHost: true,
      createdAt: new Date(new Date(lastMonthDate3).getTime() - 2 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(new Date(lastMonthDate3).getTime() - 1 * 60 * 60 * 1000).toISOString(),
      metadata: {
        department: 'HR',
        trainingType: 'Onboarding',
        participants: 'New Hires',
      },
      rating: 0,
      icsUid: 'ics_uid_131',
      attendees: [
        {
          name: 'David Brown',
          email: 'david.brown@example.com',
          timeZone: 'America/New_York',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567894',
        },
        {
          name: 'Eve Wilson',
          email: 'eve.wilson@example.com',
          timeZone: 'America/Chicago',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567895',
        },
      ],
      guests: [],
      bookingFieldsResponses: {
        department: 'Engineering',
        experience: 'Junior',
        startDate: '2024-12-01',
      },
    },
    {
      id: 132,
      uid: 'booking_uid_132',
      title: 'Sprint Planning',
      description: 'Planning the next development sprint.',
      hosts: [
        {
          id: 10,
          name: 'Mark Thompson',
          email: 'mark.thompson@example.com',
          username: 'markt',
          timeZone: 'Europe/Berlin',
        },
      ],
      status: 'completed',
      start: currentMonthDate6,
      end: new Date(new Date(currentMonthDate6).getTime() + 60 * 60 * 1000).toISOString(),
      duration: 60,
      eventTypeId: 59,
      eventType: {
        id: 10,
        slug: 'sprint-planning',
      },
      meetingUrl: 'https://meet.google.com/ghi-jklm-nop',
      location: 'https://meet.google.com/ghi-jklm-nop',
      absentHost: false,
      createdAt: new Date(new Date(currentMonthDate6).getTime() - 15 * 60 * 1000).toISOString(),
      updatedAt: new Date(new Date(currentMonthDate6).getTime() + 60 * 60 * 1000).toISOString(),
      metadata: {
        department: 'Engineering',
        sprint: 'Sprint 15',
        team: 'Frontend',
      },
      rating: 4,
      icsUid: 'ics_uid_132',
      attendees: [
        {
          name: 'John Doe',
          email: 'john@example.com',
          timeZone: 'America/New_York',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567890',
        },
        {
          name: 'Alice Smith',
          email: 'alice.smith@example.com',
          timeZone: 'America/Chicago',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567891',
        },
        {
          name: 'Bob Johnson',
          email: 'bob.johnson@example.com',
          timeZone: 'America/Denver',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567892',
        },
        {
          name: 'Carol Williams',
          email: 'carol.williams@example.com',
          timeZone: 'America/Los_Angeles',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567893',
        },
        {
          name: 'David Brown',
          email: 'david.brown@example.com',
          timeZone: 'America/New_York',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567894',
        },
      ],
      guests: [],
      bookingFieldsResponses: {
        sprint: 'Sprint 15',
        focus: 'Performance Optimization',
        capacity: '80%',
      },
    },
    {
      id: 133,
      uid: 'booking_uid_133',
      title: 'Client Check-in',
      description: 'Regular check-in with existing client.',
      hosts: [
        {
          id: 11,
          name: 'Rachel Green',
          email: 'rachel.green@example.com',
          username: 'rachelg',
          timeZone: 'America/New_York',
        },
      ],
      status: 'rescheduled',
      reschedulingReason: 'Client requested earlier time',
      rescheduledByEmail: 'client.manager@example.com',
      rescheduledFromUid: 'booking_uid_133_old',
      rescheduledToUid: 'booking_uid_133',
      start: threeMonthsAgoDate3,
      end: new Date(new Date(threeMonthsAgoDate3).getTime() + 45 * 60 * 1000).toISOString(),
      duration: 45,
      eventTypeId: 60,
      eventType: {
        id: 11,
        slug: 'client-checkin',
      },
      meetingUrl: 'https://zoom.us/j/1111222333?pwd=meeting789xyz',
      location: 'https://zoom.us/j/1111222333?pwd=meeting789xyz',
      absentHost: false,
      createdAt: new Date(new Date(threeMonthsAgoDate3).getTime() - 2 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(new Date(threeMonthsAgoDate3).getTime() - 1 * 60 * 60 * 1000).toISOString(),
      metadata: {
        department: 'Account Management',
        clientTier: 'Enterprise',
        relationship: 'Long-term',
      },
      rating: 5,
      icsUid: 'ics_uid_133',
      attendees: [
        {
          name: 'Alice Smith',
          email: 'alice.smith@example.com',
          timeZone: 'America/Chicago',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567891',
        },
        {
          name: 'Bob Johnson',
          email: 'bob.johnson@example.com',
          timeZone: 'America/Denver',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567892',
        },
        {
          name: 'Carol Williams',
          email: 'carol.williams@example.com',
          timeZone: 'America/Los_Angeles',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567893',
        },
      ],
      guests: ['finance@example.com'],
      bookingFieldsResponses: {
        company: 'Enterprise Solutions Inc',
        contract: 'Annual',
        renewal: 'Q2 2025',
      },
    },
    {
      id: 134,
      uid: 'booking_uid_134',
      title: 'Design Review',
      description: 'Reviewing UI/UX designs for new feature.',
      hosts: [
        {
          id: 12,
          name: 'Oliver Kim',
          email: 'oliver.kim@example.com',
          username: 'oliverk',
          timeZone: 'Asia/Seoul',
        },
      ],
      status: 'completed',
      start: currentMonthDate,
      end: new Date(new Date(currentMonthDate).getTime() + 75 * 60 * 1000).toISOString(),
      duration: 75,
      eventTypeId: 61,
      eventType: {
        id: 12,
        slug: 'design-review',
      },
      meetingUrl: 'https://app.cal.com/video/design-review-ui',
      location: 'https://app.cal.com/video/design-review-ui',
      absentHost: false,
      createdAt: new Date(new Date(currentMonthDate).getTime() - 20 * 60 * 1000).toISOString(),
      updatedAt: new Date(new Date(currentMonthDate).getTime() + 75 * 60 * 1000).toISOString(),
      metadata: {
        department: 'Design',
        feature: 'User Dashboard',
        version: 'v2.0',
      },
      rating: 4,
      icsUid: 'ics_uid_134',
      attendees: [
        {
          name: 'John Doe',
          email: 'john@example.com',
          timeZone: 'America/New_York',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567890',
        },
        {
          name: 'David Brown',
          email: 'david.brown@example.com',
          timeZone: 'America/New_York',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567894',
        },
        {
          name: 'Eve Wilson',
          email: 'eve.wilson@example.com',
          timeZone: 'America/Chicago',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567895',
        },
      ],
      guests: ['product.manager@example.com'],
      bookingFieldsResponses: {
        feature: 'User Dashboard Redesign',
        priority: 'High',
        targetUsers: 'Premium',
      },
    },
    {
      id: 135,
      uid: 'booking_uid_135',
      title: 'Weekly 1-on-1',
      description: 'Regular weekly check-in with team member.',
      hosts: [
        {
          id: 13,
          name: 'Lisa Anderson',
          email: 'lisa.anderson@example.com',
          username: 'lisaa',
          timeZone: 'America/New_York',
        },
      ],
      status: 'upcoming',
      start: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
      end: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000 + 30 * 60 * 1000).toISOString(),
      duration: 30,
      eventTypeId: 62,
      eventType: {
        id: 13,
        slug: 'weekly-1on1',
      },
      meetingUrl: 'https://app.cal.com/video/weekly-checkin',
      location: 'https://app.cal.com/video/weekly-checkin',
      absentHost: false,
      createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      metadata: {
        department: 'Engineering',
        meetingType: 'Recurring',
        frequency: 'Weekly',
      },
      rating: 0,
      icsUid: 'ics_uid_135',
      attendees: [
        {
          name: 'John Doe',
          email: 'john@example.com',
          timeZone: 'America/New_York',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567890',
        },
      ],
      guests: [],
      bookingFieldsResponses: {
        employee: 'John Doe',
        department: 'Engineering',
        role: 'Senior Developer',
      },
    },
    {
      id: 136,
      uid: 'booking_uid_136',
      title: 'Monthly Team Sync',
      description: 'Monthly recurring team synchronization meeting.',
      hosts: [
        {
          id: 14,
          name: 'Michael Park',
          email: 'michael.park@example.com',
          username: 'michaelp',
          timeZone: 'America/Los_Angeles',
        },
      ],
      status: 'recurring',
      start: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
      end: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000 + 60 * 60 * 1000).toISOString(),
      duration: 60,
      eventTypeId: 63,
      eventType: {
        id: 14,
        slug: 'monthly-team-sync',
      },
      meetingUrl: 'https://meet.google.com/recurring-team-sync',
      location: 'https://meet.google.com/recurring-team-sync',
      absentHost: false,
      createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      metadata: {
        department: 'Product',
        recurring: true,
        frequency: 'Monthly',
        dayOfMonth: 'First Monday',
      },
      rating: 0,
      icsUid: 'ics_uid_136',
      attendees: [
        {
          name: 'Alice Smith',
          email: 'alice.smith@example.com',
          timeZone: 'America/Chicago',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567891',
        },
        {
          name: 'Bob Johnson',
          email: 'bob.johnson@example.com',
          timeZone: 'America/Denver',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567892',
        },
        {
          name: 'Carol Williams',
          email: 'carol.williams@example.com',
          timeZone: 'America/Los_Angeles',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567893',
        },
      ],
      guests: [],
      bookingFieldsResponses: {
        team: 'Product Team',
        focus: 'Roadmap Review',
        participants: 'All Team Members',
      },
    },
    {
      id: 137,
      uid: 'booking_uid_137',
      title: 'Q4 Retrospective',
      description: 'Quarterly retrospective meeting to review past quarter.',
      hosts: [
        {
          id: 15,
          name: 'Sarah Martinez',
          email: 'sarah.martinez@example.com',
          username: 'sarahm',
          timeZone: 'America/Chicago',
        },
      ],
      status: 'past',
      start: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
      end: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000 + 90 * 60 * 1000).toISOString(),
      duration: 90,
      eventTypeId: 64,
      eventType: {
        id: 15,
        slug: 'quarterly-retro',
      },
      meetingUrl: 'https://zoom.us/j/retro-q4-2024',
      location: 'https://zoom.us/j/retro-q4-2024',
      absentHost: false,
      createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000 + 90 * 60 * 1000).toISOString(),
      metadata: {
        department: 'Engineering',
        quarter: 'Q4 2024',
        meetingType: 'Retrospective',
      },
      rating: 5,
      icsUid: 'ics_uid_137',
      attendees: [
        {
          name: 'John Doe',
          email: 'john@example.com',
          timeZone: 'America/New_York',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567890',
        },
        {
          name: 'Alice Smith',
          email: 'alice.smith@example.com',
          timeZone: 'America/Chicago',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567891',
        },
        {
          name: 'Bob Johnson',
          email: 'bob.johnson@example.com',
          timeZone: 'America/Denver',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567892',
        },
      ],
      guests: [],
      bookingFieldsResponses: {
        quarter: 'Q4 2024',
        focus: 'Team Performance',
        outcomes: 'Action Items',
      },
    },
    {
      id: 138,
      uid: 'booking_uid_138',
      title: 'New Feature Proposal',
      description: 'Proposing a new feature for product roadmap.',
      hosts: [
        {
          id: 16,
          name: 'Tom Wilson',
          email: 'tom.wilson@example.com',
          username: 'tomw',
          timeZone: 'America/New_York',
        },
      ],
      status: 'pending',
      start: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
      end: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000 + 45 * 60 * 1000).toISOString(),
      duration: 45,
      eventTypeId: 65,
      eventType: {
        id: 16,
        slug: 'feature-proposal',
      },
      meetingUrl: 'https://app.cal.com/video/feature-proposal-xyz',
      location: 'https://app.cal.com/video/feature-proposal-xyz',
      absentHost: false,
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      metadata: {
        department: 'Product',
        priority: 'High',
        feature: 'New Dashboard',
      },
      rating: 0,
      icsUid: 'ics_uid_138',
      attendees: [
        {
          name: 'David Brown',
          email: 'david.brown@example.com',
          timeZone: 'America/New_York',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567894',
        },
        {
          name: 'Eve Wilson',
          email: 'eve.wilson@example.com',
          timeZone: 'America/Chicago',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567895',
        },
      ],
      guests: ['product.lead@example.com'],
      bookingFieldsResponses: {
        feature: 'Advanced Analytics Dashboard',
        priority: 'High',
        timeline: 'Q2 2025',
      },
    },
    {
      id: 139,
      uid: 'booking_uid_139',
      title: 'Budget Approval Meeting',
      description: 'Meeting to discuss and approve Q1 budget allocation.',
      hosts: [
        {
          id: 17,
          name: 'Patricia Taylor',
          email: 'patricia.taylor@example.com',
          username: 'patriciat',
          timeZone: 'America/New_York',
        },
      ],
      status: 'rejected',
      cancellationReason: 'Budget already approved through different channel',
      cancelledByEmail: 'finance.director@example.com',
      start: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      end: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000 + 60 * 60 * 1000).toISOString(),
      duration: 60,
      eventTypeId: 66,
      eventType: {
        id: 17,
        slug: 'budget-approval',
      },
      meetingUrl: 'https://zoom.us/j/budget-q1-2025',
      location: 'https://zoom.us/j/budget-q1-2025',
      absentHost: false,
      createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      metadata: {
        department: 'Finance',
        budget: 'Q1 2025',
        amount: '$500,000',
      },
      rating: 0,
      icsUid: 'ics_uid_139',
      attendees: [
        {
          name: 'John Doe',
          email: 'john@example.com',
          timeZone: 'America/New_York',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567890',
        },
        {
          name: 'Alice Smith',
          email: 'alice.smith@example.com',
          timeZone: 'America/Chicago',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567891',
        },
      ],
      guests: ['cfo@example.com'],
      bookingFieldsResponses: {
        quarter: 'Q1 2025',
        department: 'Engineering',
        budget: '$500,000',
      },
    },
    {
      id: 140,
      uid: 'booking_uid_140',
      title: 'Partnership Discussion',
      description: 'Initial discussion about potential partnership opportunity.',
      hosts: [
        {
          id: 18,
          name: 'Kevin Brown',
          email: 'kevin.brown@example.com',
          username: 'kevinb',
          timeZone: 'America/Los_Angeles',
        },
      ],
      status: 'unconfirmed',
      start: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
      end: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000 + 60 * 60 * 1000).toISOString(),
      duration: 60,
      eventTypeId: 67,
      eventType: {
        id: 18,
        slug: 'partnership-discussion',
      },
      meetingUrl: 'https://meet.google.com/partnership-talks',
      location: 'https://meet.google.com/partnership-talks',
      absentHost: false,
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      metadata: {
        department: 'Business Development',
        partnershipType: 'Strategic',
        stage: 'Initial',
      },
      rating: 0,
      icsUid: 'ics_uid_140',
      attendees: [
        {
          name: 'Bob Johnson',
          email: 'bob.johnson@example.com',
          timeZone: 'America/Denver',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567892',
        },
        {
          name: 'Carol Williams',
          email: 'carol.williams@example.com',
          timeZone: 'America/Los_Angeles',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567893',
        },
      ],
      guests: ['partner.rep@example.com'],
      bookingFieldsResponses: {
        company: 'Strategic Partners Inc',
        partnershipType: 'Technology Integration',
        potential: 'High Value',
      },
    },
    {
      id: 141,
      uid: 'booking_uid_141',
      title: 'Emergency Team Meeting',
      description: 'Urgent meeting to address critical production issue.',
      hosts: [
        {
          id: 19,
          name: 'Chris Johnson',
          email: 'chris.johnson@example.com',
          username: 'chrisj',
          timeZone: 'America/New_York',
        },
      ],
      status: 'accepted',
      reschedulingReason: 'Original time conflicted with other critical meeting',
      rescheduledByEmail: 'chris.johnson@example.com',
      rescheduledFromUid: 'booking_uid_141_original',
      rescheduledToUid: 'booking_uid_141',
      start: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
      end: new Date(Date.now() + 4 * 60 * 60 * 1000 + 30 * 60 * 1000).toISOString(),
      duration: 30,
      eventTypeId: 68,
      eventType: {
        id: 19,
        slug: 'emergency-meeting',
      },
      meetingUrl: 'https://app.cal.com/video/emergency-urgent',
      location: 'https://app.cal.com/video/emergency-urgent',
      absentHost: false,
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
      metadata: {
        department: 'Engineering',
        priority: 'Critical',
        issueType: 'Production Outage',
        severity: 'P0',
      },
      rating: 0,
      icsUid: 'ics_uid_141',
      attendees: [
        {
          name: 'John Doe',
          email: 'john@example.com',
          timeZone: 'America/New_York',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567890',
        },
        {
          name: 'Alice Smith',
          email: 'alice.smith@example.com',
          timeZone: 'America/Chicago',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567891',
        },
        {
          name: 'Bob Johnson',
          email: 'bob.johnson@example.com',
          timeZone: 'America/Denver',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567892',
        },
        {
          name: 'David Brown',
          email: 'david.brown@example.com',
          timeZone: 'America/New_York',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567894',
        },
      ],
      guests: ['oncall@example.com'],
      bookingFieldsResponses: {
        issue: 'Database Connection Failure',
        severity: 'P0',
        impact: 'All Users',
      },
    },
    {
      id: 142,
      uid: 'booking_uid_142',
      title: 'Investor Presentation',
      description: 'Quarterly presentation to board of investors.',
      hosts: [
        {
          id: 20,
          name: 'Amanda White',
          email: 'amanda.white@example.com',
          username: 'amandaw',
          timeZone: 'America/New_York',
        },
      ],
      status: 'accepted',
      reschedulingReason: 'Investor requested different date due to scheduling conflict',
      rescheduledByEmail: 'investor.relations@example.com',
      rescheduledFromUid: 'booking_uid_142_original',
      rescheduledToUid: 'booking_uid_142',
      start: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
      end: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000 + 120 * 60 * 1000).toISOString(),
      duration: 120,
      eventTypeId: 69,
      eventType: {
        id: 20,
        slug: 'investor-presentation',
      },
      meetingUrl: 'https://zoom.us/j/investor-q4-presentation',
      location: 'https://zoom.us/j/investor-q4-presentation',
      absentHost: false,
      createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      metadata: {
        department: 'Executive',
        quarter: 'Q4 2024',
        presentationType: 'Quarterly Review',
        audience: 'Board of Investors',
      },
      rating: 0,
      icsUid: 'ics_uid_142',
      attendees: [
        {
          name: 'Alice Smith',
          email: 'alice.smith@example.com',
          timeZone: 'America/Chicago',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567891',
        },
        {
          name: 'Carol Williams',
          email: 'carol.williams@example.com',
          timeZone: 'America/Los_Angeles',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567893',
        },
        {
          name: 'David Brown',
          email: 'david.brown@example.com',
          timeZone: 'America/New_York',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567894',
        },
      ],
      guests: ['investor1@example.com', 'investor2@example.com', 'investor3@example.com'],
      bookingFieldsResponses: {
        quarter: 'Q4 2024',
        focus: 'Financial Performance',
        audience: 'Board Members',
      },
    },
    {
      id: 143,
      uid: 'booking_uid_143',
      title: 'Customer Success Call',
      description: 'Follow-up call to ensure customer satisfaction.',
      hosts: [
        {
          id: 21,
          name: 'Nancy Davis',
          email: 'nancy.davis@example.com',
          username: 'nancyd',
          timeZone: 'America/Chicago',
        },
      ],
      status: 'cancelled',
      cancellationReason: 'Customer cancelled subscription, no longer needed',
      cancelledByEmail: 'customer@example.com',
      start: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
      end: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000 + 45 * 60 * 1000).toISOString(),
      duration: 45,
      eventTypeId: 70,
      eventType: {
        id: 21,
        slug: 'customer-success-call',
      },
      meetingUrl: 'https://app.cal.com/video/customer-success-followup',
      location: 'https://app.cal.com/video/customer-success-followup',
      absentHost: false,
      createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      metadata: {
        department: 'Customer Success',
        customerTier: 'Enterprise',
        churnRisk: 'High',
      },
      rating: 0,
      icsUid: 'ics_uid_143',
      attendees: [
        {
          name: 'Bob Johnson',
          email: 'bob.johnson@example.com',
          timeZone: 'America/Denver',
          language: 'en',
          absent: false,
          phoneNumber: '+1234567892',
        },
      ],
      guests: [],
      bookingFieldsResponses: {
        customer: 'Enterprise Corp',
        accountStatus: 'Cancelled',
        reason: 'Budget Constraints',
      },
    },
  ],
  "pagination": {
    "totalItems": 23,
    "remainingItems": 0,
    "returnedItems": 23,
    "itemsPerPage": 23,
    "currentPage": 0,
    "totalPages": 1,
    "hasNextPage": false,
    "hasPreviousPage": false
  },
  "error": {}
}
